spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:minigram-chats}
    username: ${DB_USERNAME:minigram}
    password: ${DB_PASSWORD:minigram}

  h2:
    console:
      enabled: false
