spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

server:
  sandbox:
    enabled: false

logging:
  level:
    root: WARN
    '[me.soknight.minigram.chats]': INFO
    '[org.springframework.security]': WARN
    '[org.springframework.web]': WARN

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
