ktor {
  application {
    modules = [
      me.soknight.minigram.chats.ApplicationKt.module
    ]
  }

  deployment {
    port = 8080
    port = ${?CHATS_SERVICE_PORT}
  }
}

chats {
  database {
    port = 5432
    port = ${?CHATS_DB_PORT}
    name = "minigram_chats"
    name = ${?CHATS_DB_NAME}
    url = "jdbc:postgresql://localhost:"${chats.database.port}"/"${chats.database.name}
    url = ${?CHATS_DB_URL}
    driver = "org.postgresql.Driver"
    username = ${CHATS_DB_USER}
    password = ${CHATS_DB_PASSWORD}
    maxPoolSize = 10
    minIdle = 2
  }

  jwt {
    secret = ${JWT_SECRET}
    issuer = "Minigram"
    issuer = ${?JWT_ISSUER}
    audience = "MinigramClient"
    audience = ${?JWT_AUDIENCE}
  }

  services {
    profileUrl = "http://profile-service:5000"
    profileUrl = ${?PROFILE_SERVICE_URL}
  }
}
