create table chats (
    id bigint generated by default as identity primary key,
    type varchar(64) not null,
    title varchar(255),
    owner_id bigint not null,
    last_message_id bigint,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table chat_participants (
    id bigint generated by default as identity primary key,
    chat_id bigint not null,
    user_id bigint not null,
    role varchar(16) not null,
    joined_at timestamp with time zone not null,
    constraint fk_chat_participants_chat
        foreign key (chat_id) references chats (id) on delete cascade,
    constraint uk_chat_participants_chat_id_user_id
        unique (chat_id, user_id)
);

create table messages (
    id bigint generated by default as identity primary key,
    chat_id bigint not null,
    sender_id bigint not null,
    content varchar(4000) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_messages_chat
        foreign key (chat_id) references chats (id) on delete cascade
);

alter table chats
    add constraint fk_chats_last_message
        foreign key (last_message_id) references messages (id);
