create table chats (
    id bigint generated by default as identity primary key,
    type varchar(64) not null,
    title varchar(255),
    owner_id bigint not null,
    last_message_id bigint,
    message_sequence bigint not null default 0,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table chat_members (
    chat_id bigint not null,
    user_id bigint not null,
    role varchar(16) not null,
    joined_at timestamp with time zone not null,
    constraint pk_chat_members primary key (chat_id, user_id),
    constraint fk_chat_members_chat
        foreign key (chat_id) references chats (id) on delete cascade
);

create table chat_messages (
    chat_id bigint not null,
    message_id bigint not null,
    sender_id bigint not null,
    content varchar(4000) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint pk_chat_messages primary key (chat_id, message_id),
    constraint fk_chat_messages_chat
        foreign key (chat_id) references chats (id) on delete cascade,
    constraint fk_chat_messages_sender
        foreign key (chat_id, sender_id) references chat_members (chat_id, user_id)
);
